### ISSUE TITLE
Stylesheet broken after Livereload

### ISSUE THREAD

**Issue by daslicht** [vohof/gulp-livereload#106]
Hello,
I've followed this tutorial here:

http://jpsierens.com/tutorial-livereload-nodemon-gulp/

Thats my Task:
```
gulp.task('default', function() {
	// listen for changes
	livereload.listen();
	// configure nodemon
	nodemon({
		// the script to run the app
		script: './bin/www',
		ext: 'js'
	}).on('restart', function(){
		// when the app has restarted, run livereload.
		gulp.src('app.js')
			.pipe(livereload());
			//.pipe(notify('Reloading page, please wait...'));
	})
})
```

The browser reloads as expected on file change, but the stylesheet is broken after automatic reload.
The console shows:
```
GET http://localhost:3000/stylesheets/style.css net::ERR_CONNECTION_REFUSED
```

If I manually refresh the browser its back again. 

idea?

**Comment by leo** [comment]
Hey, @daslicht ! Just wanted to let you know that I've created a standalone fork of this repo, since it doesn't seem to be maintained anymore. You can find it [here](https://github.com/leo/gulp-refresh).

So I might be a good idea to re-open this issue there.

**Comment by daslicht** [comment]
thank you for the info
