### ISSUE TITLE
Option 'quiet' is actually supposed to be 'silent'

### ISSUE THREAD

**Issue by TrevorJTClarke** [vohof/gulp-livereload#107]
I was unable to get quiet to work, however adding `silent: true` worked.

**Comment by leo** [comment]
Hey, @TrevorJTClarke ! Just wanted to let you know that I've created a standalone fork of this repo, since it doesn't seem to be maintained anymore. You can find it [here](https://github.com/leo/gulp-refresh).

So I might be a good idea to re-open this issue there.

**Comment by TrevorJTClarke** [comment]
@leo appreciate it!

**Comment by leo** [comment]
@TrevorJTClarke Since this has already been discussed in the new issue, I think it'a a good idea to close this one! :blush:
