### ISSUE TITLE
Usage with gulp.watch()

### ISSUE THREAD

**Issue by tomasdev** [vohof/gulp-livereload#11]
Given the task

``` javascript
gulp.task('watch', ['default'], function () {
    gulp.watch(paths.src.js,   ['jshint']);
    gulp.watch(paths.src.css,  ['sass']);
});
```

It would be lovely to be able somehow to plug gulp-livereload (`livereload()`) there, without touching the inner tasks their selves (`jshint`, `sass`) - Do you think this could be possible?

`.watch()` doesn't return a pipe, but an EventEmitter object, which on `change` returns a data object containing the path of the modified / added / deleted file.

So far, I can think of only two "solutions":
1. Add `.pipe(livereload())` to every children task.
2. Do `gulp.watch(path.src.root, 'all')` where `all` is the task that calls to both `jshint` and `sass`, and `root` is a glob with `**/*`

But it would be quite lovely to be able to trigger somehow "hey X file changed." (something like exposing `server.changed` maybe?)

I don't really know how this all messes with streams... **What do you think?**

**Comment by julio899** [comment]
I use, the following, in my Gulpfile.js
`var gulp = require('gulp'),
    livereload = require('gulp-livereload'),
    watch = require('gulp-watch');

    // Rerun the task when a file changes
    gulp.task('default', function () {
      
        livereload.listen();
            reloadPage = function (evt) {
                livereload.changed(evt.path);
            };

        gulp.watch('./*.php', reloadPage);
    });`
Something simple greetings.
