### ISSUE TITLE
New, maintained fork

### ISSUE THREAD

**Issue by leo** [vohof/gulp-livereload#113]
Hey!

Just wanted to let you know that your repo seems to be unmaintained since quite a long time and I've therefore decided to fork it: https://github.com/leo/gulp-refresh

If you decide to work on it again, I'd be happy to add you as a collaborator. :blush:

**Comment by lirantal** [comment]
@leo did the maintainer ever contact you? did you get any feedback?

**Comment by leo** [comment]
@lirantal Nope. Sadly not...
