### ISSUE TITLE
Security Issue: Remove `event-stream` dependency.

### ISSUE THREAD

**Issue by TheSeg** [vohof/gulp-livereload#139]
[As noted in this issue](https://github.com/dominictarr/event-stream/issues/116), `event-stream` is compromised and the original maintainer doesn't have control over the repo.

**Comment by backflip** [comment]
Locking it to `3.3.4` might be a quick fix for now (and `npm` has taken ownership of the package in the meantime).

**Comment by ragesoss** [comment]
I note that the bad version has been yanked from npm, but the current default with `gulp-reload` will be to include `3.3.5`, which is (I guess?) benign but does include (only) changes by the bad actor who went on to add the malicious code in `3.3.6`.
