### ISSUE TITLE
Infinite loop in version 4.0.2

### ISSUE THREAD

**Issue by jrmarqueshd** [vohof/gulp-livereload#143]
Hello developers!
In today's release of version [https://www.npmjs.com/package/gulp-livereload/v/4.0.2](4.0.2) on npm, I noticed that calling the livereload.listen method is causing an infinite loop at the moment the file is saved.

**Comment by klimashkin** [comment]
That is kind of suspicious version, I don't see corresponding commit or tag in this repo

**Comment by jrmarqueshd** [comment]
I checked again and noticed that the error was being caused for another reason, sorry and thanks.
