### ISSUE TITLE
when there's no parameter 

### ISSUE THREAD

**Issue by Daniel-Xu** [vohof/gulp-livereload#15]
If there's no port or server passed to liveload()

there will be an error: 

... Uhoh. Got error listen EADDRINUSE ...
Error: listen EADDRINUSE

**Comment by sivan** [comment]
How can I catch errors?
Sometimes it happens because there's another livereload proccess running for another gulp task.
I want to warn users when they get the error `EADDRINUSE` and tell them turn down other gulp task in terminal.
