### ISSUE TITLE
Change not triggered on nodemon restart

### ISSUE THREAD

**Issue by xpepermint** [vohof/gulp-livereload#38]
``` javascript
var nodemon = require('gulp-nodemon')
var livereload = require('gulp-livereload');

gulp.task('app:start', function () {
  var reload =  require('gulp-livereload')();
  nodemon({
    script: './config/boot.js',
    ext: 'js json coffee css less scss html'
  }).on('restart', function() {
    console.log("RESTARTED");
    reload.changed()
  })
})
```

The browser is not reloading but I see the `[xx:xx:xx] * was reloaded.` and `RESTARTED` in the console.

**Comment by wzup** [comment]
The same here. Chrome Plugin is on and browser doesn't reload. Here is my issue with my gulpfile.js:
https://github.com/vohof/gulp-livereload/issues/63

**Comment by vohof** [comment]
Added a [nodemon example](https://github.com/vohof/gulp-livereload/tree/master/examples/nodemon)
