### ISSUE TITLE
Reloading all linked stylesheets, instead of one sent via websocket notification

### ISSUE THREAD

**Issue by Most** [vohof/gulp-livereload#5]
livereload.js is unable properly match stylesheet to be reloaded, due to backslashes used as uri segments separators inside websocket notification. As a result, all stylesheets declared inside <link> tag are being fetched.

Replacing all backslashes with forward slashes fixes issue.

``` javascript
module.exports = function (server) {
  var map = require('map-stream');

  var changed = function (file, cb) {   
    server.changed({
      body: {
        files: [file.path.replace(/\\/g,'/')]
        /* files: [file.path] */
      }
    });

    cb(null, file);
  };

  return map(changed);
};
```

Some screens made while debugging livereload.js:
Before slash replacement

![image](https://f.cloud.github.com/assets/200261/2015112/3a688266-87b2-11e3-8b8b-e10e2190471d.png)
After fix

![image](https://f.cloud.github.com/assets/200261/2015138/df04fe8a-87b2-11e3-96eb-c2a9b217467a.png)

**Comment by graham73may** [comment]
Is this related to this issue? I'm having OS specific problems that sound very similar to this.
https://github.com/livereload/livereload-js/issues/97
