### ISSUE TITLE
Equivalent for refresh on change

### ISSUE THREAD

**Issue by barbuslex** [vohof/gulp-livereload#54]
Hi,

Can you tell me the equivalent code for the new version of gulp-livereload  : 

``` javascript
var server = livereload();
  gulp.watch(dest + '/**').on('change', function(file) {
      server.changed(file.path);
  });
```

When i use it i take this error message : 

> server.changed(file.path);
> -----------^
> TypeError: Object #<Stream> has no method 'changed'

How can i solve it ?

Thanks

**Comment by wcoding** [comment]
Thank you vohof, I have a similar case.

**Comment by LukyVj** [comment]
Thank you @vohof  !
