### ISSUE TITLE
Add host parameter

### ISSUE THREAD

**Issue by fedosov** [vohof/gulp-livereload#57]
I can't use `gulp-livereload` with mobile devices, because `lr` server binds to `127.0.0.1` but not `0.0.0.0`.
Maybe I can specify `0.0.0.0` address somehow (for now I see only `port` parameter that I can pass with `livereload.listen` call)? Or it is not possible in current implementation?

**Comment by vohof** [comment]
@fedosov thanks! Fixed in `3.1.0`.

**Comment by fedosov** [comment]
Awesome, thanks!
