### ISSUE TITLE
Where did livereload.js go?

### ISSUE THREAD

**Issue by akbr** [vohof/gulp-livereload#60]
Just updated from v2.1.1 to v3.2.0.

I was relying on livereload.js, provided at "//[server]:35729/livereload.js", for a remote connection. But since updating, the javascript file has disappeared.

Is the javascript file still provided by gulp-livereload? Is there a better way to use livereload remotely? (The Chrome plugin seems restricted to localhost.)

**Comment by vohof** [comment]
@akbr, it's still there. Have you called `.listen()` first?

**Comment by akbr** [comment]
@vohof Yup.

Here's a the gulpfile:
```javascript
var gulp = require('gulp');
var livereload = require('gulp-livereload');

gulp.task('watch', function() {
  livereload.listen();
  gulp.watch(['*.js', '*.html'], livereload.changed);
});

gulp.task("default", ['watch']);
```

and here's the relevant part of my index.html:
```
    <script>
      document.write('<script src="//' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>');
    </script>
```

This works with v2.1.1. But after updating to v3.2.0 -- changing nothing in either file -- I lose access to livereload.js from the browser (GET http://[mydevdomain]:35729/livereload.js net::ERR_CONNECTION_REFUSED).
