### ISSUE TITLE
silent mode is not so silent anymore

### ISSUE THREAD

**Issue by DarkPark** [vohof/gulp-livereload#62]
version 3.3.0

despite the silent flag:
```js
var livereload = require('gulp-livereload');
livereload.listen({silent: true});
```
there is still log output:
```
[11:16:39] /home/dp/Projects/web/test/stb-demo/build/develop/css/720.css reloaded.
```
it's not desired behavior as I handle all logging by myself.

this code seems to blame - https://github.com/vohof/gulp-livereload/blob/322ba3a5da482e793f9f8856a4f248d65dd4c72b/index.js#L50

**Comment by ArnaudRinquin** [comment]
I just fixed that through the `quiet` option I add in #64. Wait for it to get merged or use my branch.

**Comment by vohof** [comment]
thanks @ArnaudRinquin.

**Comment by DarkPark** [comment]
:+1:
