### ISSUE TITLE
sugar for forcing a full page reload

### ISSUE THREAD

**Issue by contra** [vohof/gulp-livereload#66]
any way to do this currently other than `require('gulp-livereload').changed(indexPath)` ?

**Comment by vohof** [comment]
Not currently.

**Comment by contra** [comment]
@vohof Would be cool to figure out some way to do this :+1:

**Comment by vohof** [comment]
It looks like passing anything other than a css file reloads the page so I just passed an `index.html` file.

**Comment by contra** [comment]
@vohof Nice thanks! Published to npm?

**Comment by vohof** [comment]
@contra yes  :sparkles: :sparkles:
