### ISSUE TITLE
Livereload with PHP server on port 80

### ISSUE THREAD

**Issue by martinkovac** [vohof/gulp-livereload#67]
I have webserver running at port 80 with PHP. I can use PHP only at this port. If I want to reload browser I must open browser on this port 80. But when I set `livereload.listen(80)` I got error EADDRINUSE - its because this port is already in use. So how can I livereload my browser on page that must run on port 80 with PHP?
Thanks

**Comment by vohof** [comment]
Livereload has to listen on another port. By default it listens to port `35729`.

**Comment by martinkovac** [comment]
Yes I know that default port is 35729. I have set port to 80 as I write before but I get an error. Have you try to run livereload with PHP server?

**Comment by vohof** [comment]
Yes, but you cannot have them both listening on the same port.

>  So how can I livereload my browser on page that must run on port 80 with PHP?

Just let livereload listen on the default port, php server on port 80.

**Comment by martinkovac** [comment]
If I do this then livereload doesn't work - don't know why. I have just added script manually using browser extension. This is working fine. But why I need to add `<script src="http://localhost:35729/livereload.js?snipver=1"></script>` manually?
Thanks for advice.

**Comment by vohof** [comment]
Can you open chrome devtools and check for error messages?

**Comment by martinkovac** [comment]
There is no error at all :(

**Comment by vohof** [comment]
You might want to submit an issue [here](https://github.com/mockko/livereload/issues), it does not appear to be a problem with this module.

**Comment by martinkovac** [comment]
OK the problem was between table and the chair - I didn't see that livereload plugin was not enabled. After I enable it it is OK now. But one question is still remaining - why when I change some styles or html template and save it then call `.pipe(livereload())` browser refresh but it looks like at the state before save. If I change something new after it, it will refresh the page again but with the previous save state. It looks like it is one state behind. I run `.pipe(livereload())` after any CSS and HTML change.

**Comment by vohof** [comment]
Can I look at the whole task?

**Comment by martinkovac** [comment]
Yes of course:

```javascript
gulp.task('watch', function () {
    $.livereload.listen({
        basePath: 'dist',
        port: 35729
    });

    gulp.watch('app/**/*.{html,tpl,phtml,php,js}', ['templates', 'minify-scripts']);
    gulp.watch('app/less/**/*.less', ['styles', 'minify-styles']);

    // Notify Livereload when changed
    gulp.watch([
        '.tmp/**/*.{html,tpl,phtml,php,css,js,json}',
        'app/images/**/*',
        'app/fonts/**/*'
    ]).on('change', $.livereload.changed);
});
```

and for example task for styles:

```javascript
gulp.task('styles', function () {
    return gulp.src(['app/less/*.less'])
            .pipe(using({prefix: 'Using less file', color: 'yellow'}))
            .pipe($.less())
            .on('error', function (err) {
                console.log(err.message);
            })
            .pipe($.autoprefixer({browsers: ['last 1 version']}))
            .pipe(gulp.dest('.tmp/styles'))
            .pipe(gulp.dest('dist/styles'))
            .pipe($.livereload());
});
```

I'm using gulp-load-plugins: `var $ = require('gulp-load-plugins')();`

Hope it helps. Thanks

**Comment by vohof** [comment]
If it's a css that gets reloaded it shouldn't need a full page reload, you should immediately see the changes. Can I see the task which does a page reload?

**Comment by martinkovac** [comment]
Sorry for delay, here is the task for building templates:

```javascript
gulp.task('templates', ['styles'], function () {

    var assets = $.useref.assets({searchPath: '{.tmp,app}'});

    return gulp.src(['app/**/*.{html,tpl,phtml,php}'])
            .pipe(using({prefix: 'Using template file', color: 'yellow'}))
            .pipe(assets)
            .pipe(assets.restore())
            .pipe($.useref())
            .pipe(gulp.dest('.tmp'))
            .pipe(gulp.dest('dist'))
            .pipe($.livereload());
});
```
