### ISSUE TITLE
livereload server's livereload.js occasionally not working

### ISSUE THREAD

**Issue by Nessworthy** [vohof/gulp-livereload#72]
So, aside from the chrome extension, the livereload server has a JS file which uses websockets to detect and trigger page reloads.

When I was only using this to react to CSS changes, it worked fine (and incredibly fast!), but I've since I've also now added a livereload trigger for my php file, it will occasionally break with a rather generic error message (in firefox's console):

    Firefox can't establish a connection to the server at ws://localhost:35729/livereload.
    ReferenceError: ProtocolError is not defined

After breaking, the livereload script does not trigger any updates until a page refresh resets it. There's also no abnormal messages in the terminal which is running the watch command.

Relevant gulpfile snippet:

    var gulp = require('gulp'),
        watch = require('gulp-watch');
        livereload = require('gulp-livereload');

    livereload.options.port = 35729;

    gulp.task('watch', function() {
        livereload.listen();
        gulp.watch(['index.php', 'script.js'], ['reload']);
    });

    gulp.task('reload', function() {

        gulp
            .src('index.php')
            .pipe(livereload());

    });

As I've said I've been using it for CSS changes too and it has worked without any issues. It's only started occurring after I added the task and watch command shown above.

My simple package.json:

    "gulp"            : "3.8.x",
    "gulp-watch"      : "3.0.x",
    "gulp-livereload" : "3.6.x"

At the bottom of my index.php:

    <script src="//localhost:35729/livereload.js"></script>

I was first wondering if this was specific to this gulp package, as I've previously used grunt + LR without any problems. If not, I'll try and drop straight down into livereload's repo instead.

**Comment by vohof** [comment]
> ReferenceError: ProtocolError is not defined

it usually shows which line caused that error. Can you point out which line it is?

https://github.com/zaius/livereload-js/blob/master/dist/livereload.js

**Comment by GEnghusen** [comment]
I'm receiving this same error for a while now.
Here is my error stack

```
Uncaught ReferenceError: ProtocolError is not defined | livereload.js?snipver=1:345
exports.LiveReload.LiveReload.connector.Connector.error | livereload.js?snipver=1:345
exports.Connector.Connector.protocolParser.Parser.error | livereload.js?snipver=1:31
exports.Parser.Parser.process | livereload.js?snipver=1:614
exports.Connector.Connector._onmessage | livereload.js?snipver=1:165
(anonymous function) | livereload.js?snipver=1:87
```

gulp.js file trimmed down to important lines/functions
```
gulp.task('sass', function() {
	gulp.src(['./assets/scss/style.scss'])
		.pipe(sass({
			style: 'compressed',
			errLogToConsole: true
		}))
		.pipe(gulp.dest('./assets/css/'))
		.pipe(livereload());
});

gulp.task('watch', function () {
	livereload.listen();
	gulp.watch(['./assets/scss/**.scss','./assets/scss/**/**.scss'], ['sass']);
});
```

package.json also trimmed down
```
"gulp"            : "3.8.10",
"gulp-sass"       : "0.7.3",
"gulp-watch"      : "4.1.0",
"gulp-livereload" : "3.7.0",
```

**Comment by nauman** [comment]
same error here 

Uncaught ReferenceError: ProtocolError is not definedlivereload.js?snipver=1:345 exports.LiveReload.LiveReload.connector.Connector.errorlivereload.js?snipver=1:31 exports.Connector.Connector.protocolParser.Parser.errorlivereload.js?snipver=1:614 exports.Parser.Parser.processlivereload.js?snipver=1:165 exports.Connector.Connector._onmessagelivereload.js?snipver=1:87 (anonymous function)

any resolution for that?

**Comment by rickihastings** [comment]
I'm also getting this problem, it's coming from `livereload-js` though. On line https://github.com/livereload/livereload-js/blob/master/dist/livereload.js#L345

**Comment by redders6600** [comment]
I also get this.. Same line.

**Comment by zaggino** [comment]
@vohof Could this be re-opened? Getting the same as people above:
![image](https://cloud.githubusercontent.com/assets/1067319/7290448/6040c282-e9c2-11e4-9d44-4a076c673cb5.png)

**Comment by nomuna** [comment]
I am getting this error too. The issue is not gone.

**Comment by Jazcash** [comment]
Anyone found a fix for this issue?

**Comment by andrewchilds** [comment]
Here's what I'm seeing, along with the stack trace:

```
Uncaught ReferenceError: ProtocolError is not defined
    LiveReload.connector.Connector.error   @ livereload.js:345
    Connector.protocolParser.Parser.error  @ livereload.js:31
    exports.Parser.Parser.process          @ livereload.js:614
    exports.Connector.Connector._onmessage @ livereload.js:165
    (anonymous function)                   @ livereload.js:87
```

![image](https://cloud.githubusercontent.com/assets/352089/17381687/20cd0aee-599b-11e6-9093-6a54589edba8.png)

**Comment by thezoid** [comment]
I still get this

**Comment by tbremer** [comment]
I get this from time to time as well.
