### ISSUE TITLE
cannot connect with firefox

### ISSUE THREAD

**Issue by Mech7** [vohof/gulp-livereload#74]
I get the following from the console when i run in debug.

  tinylr:server LiveReload handler /livereload (middleware: off) +669ms
  tinylr:server Parse +0ms undefined undefined
  tinylr:server Body parsed +0ms {}
  tinylr:server query parsed +1ms {} undefined
  tinylr:server Request: +1ms GET /livereload

**Comment by vohof** [comment]
Forgot to call `.listen()`?

**Comment by vohof** [comment]
What error are you getting.

**Comment by Mech7** [comment]
Could not connect to LiveReload server. Please make sure that a compatible LiveReload server is running. (We recommend guard-livereload, until LiveReload 2 comes to your platform.)

On chrome it does work

**Comment by Mech7** [comment]
I see the js is being send as json too instead of javascript.
http://127.0.0.1:35729/livereload.js?ext=Firefox&extver=2.0.9
Content-Type: application/json
