### ISSUE TITLE
Inject new JavaScript without page refresh

### ISSUE THREAD

**Issue by bkolobara** [vohof/gulp-livereload#77]
Right now when I change a CSS files the changes are automatically injected into the browser without a refresh. I would like to have the same behavior for JavaScript. This means reevaluate the JavaScript file again but don't refresh the page to preserve state.

**Comment by itsthatguy** [comment]
I am seeing the entire page page refresh when changing CSS.

**Comment by roelvanhintum** [comment]
@bkolobara Is it even possible to do that? JS code is instantiated and has states, which makes it really difficult to just change it.

@itsthatguy I'm having the same issue, but it's a different one than @bkolobara is referring to.

**Comment by bkolobara** [comment]
@roelvanhintum Yes, if you use appropriate JS libraries. It will not work if you don't plan upfront for it. I was hoping to archive the react-hot-loader experience (https://vimeo.com/100010922).

In the meantime I switched to webpack and didn't look deeper into livereload.

@itsthatguy I don't this the entire page was refreshing, but maybe I'm wrong and it was ultra fast.

**Comment by roelvanhintum** [comment]
@bkolobara Thanks, i completely missed this.
