### ISSUE TITLE
livereload.js is missing

### ISSUE THREAD

**Issue by oleghind** [vohof/gulp-livereload#83]
Trying to install gulp-livereload, but it doesn't come with the livereload.js

c:\wamp\appdir>npm install
gulp-livereload@3.8.0 node_modules\gulp-livereload
├── debug@2.1.3 (ms@0.7.0)
├── event-stream@3.3.0 (stream-combiner@0.0.4, from@0.1.3, duplexer@0.1.1, map-
tream@0.1.0, pause-stream@0.0.11, split@0.3.3, through@2.3.7)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@
.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
└── tiny-lr@0.1.5 (parseurl@1.3.0, qs@2.2.5, debug@2.0.0, body-parser@1.8.4, fa
e-websocket@0.7.3)

I have to manually add livereload.js to the tiny-lr node_modules folder

**Comment by vohof** [comment]
See #97.
