### ISSUE TITLE
Chrome on iOS doesn't finish loading

### ISSUE THREAD

**Issue by evjan** [vohof/gulp-livereload#90]
When hitting my local Rails server using Chrome on my iPhone, the page rarely seems to finish loading, which means I can't get any JS functionality to work on the page. In Safari it is fine.

I tested only having livereload loaded on an empty page, and without it the page loads fine, with it it keeps loading a very long tim.

Tested on iPhone 4S, iPhone 5S and iPhone 6. iOS 8.4.1. Latest Chrome. Livereload 3.8.0.

Let me know if you need more info!

**Comment by vohof** [comment]
You should be able to find what's not finished loading on devtools in the Network tab.
