### ISSUE TITLE
Installing with npm 3 throws ENOENT

### ISSUE THREAD

**Issue by phparkle** [vohof/gulp-livereload#94]
This was working fine until I upgraded to npm 3. When I gulp watch, it starts listening, but as soon as I load the page that requests the livreload script, it throws this:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'path/to/project/node_modules/tiny-lr/node_modules/livereload-js/dist/livereload.js'
    at Error (native)
```

**Comment by phparkle** [comment]
Using tiny-lr from github instead of npm fixes this for now 0132bebbf7429d234a3981536a96461875f8bd41

**Comment by DarkPark** [comment]
https://github.com/mklabs/tiny-lr/issues/91

**Comment by elwayman02** [comment]
@phparkle @DarkPark I've submitted a PR with a more permanent solution.
